import { Quote } from './types';

export const quotes: Quote[] = [
  { quote: "Do not save what is left after spending, but spend what is left after saving.", author: "Warren Buffett" },
  { quote: "Discipline is choosing between what you want now and what you want most.", author: "Abraham Lincoln" },
  { quote: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { quote: "Small daily improvements over time lead to stunning long-term results.", author: "Robin Sharma" },
  { quote: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin" },
  { quote: "The rich rules over the poor, and the borrower is the slave of the lender.", author: "Proverbs 22:7" },
  { quote: "Compound interest is the eighth wonder of the world. He who understands it, earns it; he who doesn't, pays it.", author: "Albert Einstein" },
  { quote: "It’s not how much money you make, but how much money you keep, how hard it works for you, and how many generations you keep it for.", author: "Robert Kiyosaki" },
  { quote: "Never depend on single income. Make investment to create a second source.", author: "Warren Buffett" },
  { quote: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn" },
  { quote: "Rich people believe 'I create my life.' Poor people believe 'Life happens to me.'", author: "T. Harv Eker" },
  { quote: "Beware of little expenses; a small leak will sink a great ship.", author: "Benjamin Franklin" },
  { quote: "Money is a terrible master but an excellent servant.", author: "P.T. Barnum" },
  { quote: "A penny saved is a penny earned.", author: "Benjamin Franklin" },
  { quote: "He who buys what he does not need, steals from himself.", author: "Swedish Proverb" },
  { quote: "The goal isn't more money. The goal is living life on your own terms.", author: "Chris Brogan" },
  { quote: "Formal education will make you a living; self-education will make you a fortune.", author: "Jim Rohn" },
  { quote: "Wealth consists not in having great possessions, but in having few wants.", author: "Epictetus" },
  { quote: "Every time you borrow money, you're robbing your future self.", author: "Nathan W. Morris" },
  { quote: "The price of anything is the amount of life you exchange for it.", author: "Henry David Thoreau" },
  { quote: "Wealth is the ability to fully experience life.", author: "Henry David Thoreau" },
  { quote: "We make a living by what we get, but we make a life by what we give.", author: "Winston Churchill" },
  { quote: "The budget is not just a book of numbers but an expression of our values.", author: "Marian Wright Edelman" },
  { quote: "You must gain control over your money or the lack of it will forever control you.", author: "Dave Ramsey" },
  { quote: "Don't tell me what you value, show me your budget, and I'll tell you what you value.", author: "Joe Biden" },
  { quote: "I will prepare and some day my chance will come.", author: "Abraham Lincoln" },
  { quote: "If you want to be rich, think of saving as well as getting.", author: "Benjamin Franklin" },
  { quote: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
  { quote: "Investing should be more like watching paint dry or watching grass grow. If you want excitement, take $800 and go to Las Vegas.", author: "Paul Samuelson" },
  { quote: "It is not the man who has too little, but the man who craves more, that is poor.", author: "Seneca" },
  { quote: "The habit of saving is itself an education; it fosters every virtue, teaches self-denial, cultivates the sense of order.", author: "T.T. Munger" },
  { quote: "It is greatness of soul that makes a man rich, not a great fortune.", author: "Seneca" },
  { quote: "A budget tells us what we can't afford, but it doesn't keep us from buying it.", author: "William Feather" },
  { quote: "Discipline is the soul of an army. It makes small numbers formidable.", author: "George Washington" },
  { quote: "Wealth is not his that has it, but his that enjoys it.", author: "Benjamin Franklin" },
  { quote: "Opportunities multiply as they are seized.", author: "Sun Tzu" },
  { quote: "If we command our wealth, we shall be rich and free. If our wealth commands us, we shall be poor indeed.", author: "Edmund Burke" },
  { quote: "It is preposterous that you should be a slave to your own money.", author: "Juvenal" },
  { quote: "The most difficult thing is the decision to act, the rest is merely tenacity.", author: "Amelia Earhart" },
  { quote: "Wealth flows from energy and ideas.", author: "William Feather" },
  { quote: "A simple fact that is hard to learn is that the time to save money is when you have some.", author: "Joe Moore" },
  { quote: "Deficit spending is simply a scheme for the confiscation of wealth.", author: "Alan Greenspan" },
  { quote: "The safe way to double your money is to fold it over once and put it in your pocket.", author: "Kin Hubbard" },
  { quote: "He who has a why to live can bear almost any how.", author: "Friedrich Nietzsche" },
  { quote: "Capital as such is not evil; it is its wrong use that is evil.", author: "Mahatma Gandhi" },
  { quote: "Money is only a tool. It will take you wherever you wish, but it will not replace you as the driver.", author: "Ayn Rand" },
  { quote: "The intelligent investor is a realist who sells to optimists and buys from pessimists.", author: "Benjamin Graham" },
  { quote: "Discipline is the root of all good qualities.", author: "Jocko Willink" },
  { quote: "The stock market is filled with individuals who know the price of everything, but the value of nothing.", author: "Philip Fisher" },
  { quote: "Without frugality none can be rich, and with it very few would be poor.", author: "Samuel Johnson" },
  { quote: "If you live for having it all, what you have is never enough.", author: "Vicki Robin" },
  { quote: "Quality is not an act, it is a habit.", author: "Aristotle" },
  { quote: "There is no dignity quite so impressive, and no independence quite so important, as living within your means.", author: "Calvin Coolidge" },
  { quote: "A wise man should have money in his head, but not in his heart.", author: "Jonathan Swift" },
  { quote: "Frugality without creativity is deprivation.", author: "Amy Dacyczyn" },
  { quote: "Rule No. 1: Never lose money. Rule No. 2: Never forget rule No. 1.", author: "Warren Buffett" },
  { quote: "Money grows on the tree of persistence.", author: "Japanese Proverb" },
  { quote: "Focus on building assets rather than displaying liabilities.", author: "Unknown" },
  { quote: "True wealth is not about having a lot of money; it's about having a lot of options.", author: "Chris Rock" },
  { quote: "Discipline equals freedom.", author: "Jocko Willink" },
  { quote: "The four most dangerous words in investing are: 'This time it's different.'", author: "Sir John Templeton" },
  { quote: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier" },
  { quote: "It’s how you deal with failure that determines how you achieve success.", author: "David Feherty" },
  { quote: "Never spend your money before you have earned it.", author: "Thomas Jefferson" },
  { quote: "He who control the present controls the past, he who controls the future controls the present.", author: "George Orwell" },
  { quote: "If you don't find a way to make money while you sleep, you will work until you die.", author: "Warren Buffett" },
  { quote: "Wealth is quiet. Rich is loud. Poor is flashy.", author: "Unknown" },
  { quote: "Live like no one else now so later you can live like no one else.", author: "Dave Ramsey" },
  { quote: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
  { quote: "Wealth is what you don't see. It's the cars not purchased. The diamonds not bought.", author: "Morgan Housel" },
  { quote: "You can make excuses or you can make progress, but you cannot make both.", author: "Unknown" },
  { quote: "Do the hard work now. Enjoy the fruits later.", author: "Unknown" },
  { quote: "The compound effect is the strategy of obtaining huge rewards from small, seemingly insignificant actions.", author: "Darren Hardy" },
  { quote: "Consistency is the true foundation of trust and success.", author: "Unknown" },
  { quote: "Spend your money on the things money can buy. Spend your time on the things money can't buy.", author: "Haruki Murakami" },
  { quote: "Your net worth is a lagging measure of your financial habits.", author: "James Clear" },
  { quote: "Discipline is the refining fire by which talent becomes ability.", author: "Roy L. Smith" },
  { quote: "Do not let what you cannot do interfere with what you can do.", author: "John Wooden" },
  { quote: "He who is contented is rich.", author: "Lao Tzu" },
  { quote: "Empty pockets never held anyone back. Only empty heads and empty hearts can do that.", author: "Norman Vincent Peale" },
  { quote: "Money is like manure. If you spread it around, it does a lot of good. But if you pile it up in one place, it stinks like heaven.", author: "J.R. Clint" },
  { quote: "Happiness is not in the mere possession of money; it lies in the joy of achievement, in the thrill of creative effort.", author: "Franklin D. Roosevelt" },
  { quote: "Wealth is the product of man's capacity to think.", author: "Ayn Rand" },
  { quote: "Every dollar spent is a vote for the kind of world you want.", author: "Unknown" },
  { quote: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
  { quote: "Too many people spend money they haven't earned to buy things they don't want to impress people they don't like.", author: "Will Rogers" },
  { quote: "Buy land, they're not making it anymore.", author: "Mark Twain" },
  { quote: "Discipline is the greatest form of self-love.", author: "Unknown" },
  { quote: "Patience is a key element of success.", author: "Bill Gates" },
  { quote: "The stock market is a device for transferring money from the active to the patient.", author: "Warren Buffett" },
  { quote: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin" },
  { quote: "Great things are done by a series of small things brought together.", author: "Vincent Van Gogh" },
  { quote: "Action is the foundational key to all success.", author: "Pablo Picasso" },
  { quote: "Success seems to be connected with action. Successful people keep moving.", author: "Conrad Hilton" },
  { quote: "There is no elevator to success. You have to take the stairs.", author: "Zig Ziglar" },
  { quote: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { quote: "Courage is being scared to death, but saddling up anyway.", author: "John Wayne" },
  { quote: "Financial freedom is available to those who learn about it and work for it.", author: "Robert Kiyosaki" },
  { quote: "Out of debt, out of danger.", author: "Jerry Podany" },
  { quote: "Money is a guarantee that we may have what we want in the future.", author: "Aristotle" },
  { quote: "The desire for gold is not for gold. It is for the means of freedom and benefit.", author: "Ralph Waldo Emerson" },
  { quote: "Wealth is the progressive realization of a worthy ideal.", author: "Earl Nightingale" },
  { quote: "Borrowing money is the easiest way to lose your peace of mind.", author: "Unknown" },
  { quote: "A bank is a place that will lend you money if you can prove that you don't need it.", author: "Bob Hope" },
  { quote: "Only buy something that you'd be perfectly happy to hold if the market shut down for 10 years.", author: "Warren Buffett" },
  { quote: "Before you speak, listen. Before you write, think. Before you spend, earn.", author: "William A. Ward" },
  { quote: "Diversification is protection against ignorance.", author: "Warren Buffett" },
  { quote: "Invest in yourself. It is the best investment you will ever make.", author: "Unknown" },
  { quote: "Consistency transforms average into excellence.", author: "Unknown" },
  { quote: "Motivation gets you going, but habit is what keeps you running.", author: "Jim Ryun" },
  { quote: "The plans of the diligent lead surely to abundance, but everyone who is hasty comes only to poverty.", author: "Proverbs 21:5" },
  { quote: "If you would be wealthy, think of saving as well as getting.", author: "Benjamin Franklin" },
  { quote: "Discipline is the path to greatness.", author: "Unknown" },
  { quote: "Good habits are worth being fanatical about.", author: "John Irving" },
  { quote: "Frugality is one of the most beautiful and joyful virtues.", author: "Seneca" },
  { quote: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle" },
  { quote: "Do not put all your eggs in one basket.", author: "Warren Buffett" },
  { quote: "Risk comes from not knowing what you're doing.", author: "Warren Buffett" },
  { quote: "It is not wealth that makes life easy, but the control of wants.", author: "Epictetus" },
  { quote: "Do not tell me what you value, show me your ledger.", author: "Unknown" },
  { quote: "The best way to predict the future is to create it.", author: "Peter Drucker" },
  { quote: "Self-discipline is the number one trait needed for success.", author: "Unknown" },
  { quote: "He who has no discipline, has no freedom.", author: "Unknown" },
  { quote: "If you command your wealth, you are rich and free.", author: "Edmund Burke" },
  { quote: "To buy what you do not need is the shortest road to wanting what you do.", author: "Unknown" },
  { quote: "A clear budget is the roadmap to a free life.", author: "Unknown" },
  { quote: "The art of living is more like wrestling than dancing.", author: "Marcus Aurelius" },
  { quote: "Take care of the pennies, and the pounds will take care of themselves.", author: "English Proverb" },
  { quote: "You must save money to buy assets, not liabilities.", author: "Unknown" },
  { quote: "The secret of wealth is simple: double your savings and half your spending.", author: "Unknown" },
  { quote: "Discipline is the hallmark of the wise.", author: "Unknown" },
  { quote: "Long-term planning is not about future decisions, but about the future of present decisions.", author: "Peter Drucker" },
  { quote: "Wealth is built by habits, not luck.", author: "Unknown" },
  { quote: "Live below your means, but build beyond your dreams.", author: "Unknown" },
  { quote: "Patience and persistence have a magical effect before which difficulties disappear.", author: "John Quincy Adams" },
  { quote: "The standard of wealth is the number of days you can survive without working.", author: "Robert Kiyosaki" },
  { quote: "A tiny expense here and there soon sums to a mountain.", author: "Unknown" },
  { quote: "Spend less than you earn. That is the ultimate financial law.", author: "Unknown" },
  { quote: "Consistency is key. Do not give up.", author: "Unknown" },
  { quote: "Wealth is not about showing off. It is about staying secure.", author: "Morgan Housel" },
  { quote: "Self-control is strength. Right thought is mastery. Calmness is power.", author: "James Allen" },
  { quote: "The greatest wealth is to live content with little.", author: "Plato" },
  { quote: "A budget is telling your money where to go instead of wondering where it went.", author: "John C. Maxwell" },
  { quote: "The first step toward wealth is avoiding debt.", author: "Unknown" },
  { quote: "Discipline is the foundation of all true freedom.", author: "Unknown" },
  { quote: "Work hard in silence. Let your success make the noise.", author: "Frank Ocean" },
  { quote: "Do not let small setbacks stop you. Consistency is what matters.", author: "Unknown" },
  { quote: "He who buys what he does not need will soon have to sell what he does need.", author: "Benjamin Franklin" },
  { quote: "Invest for the long run. The short run is noise.", author: "Jack Bogle" },
  { quote: "Patience is bitter, but its fruit is sweet.", author: "Jean-Jacques Rousseau" },
  { quote: "Discipline your mind to focus on assets, not distractions.", author: "Unknown" },
  { quote: "The path to financial freedom starts with a single dollar saved.", author: "Unknown" },
  { quote: "Wealth is what you save, not what you spend.", author: "Morgan Housel" },
  { quote: "Spend time, not money, to acquire happiness.", author: "Unknown" },
  { quote: "Discipline is the shortcut to success.", author: "Unknown" },
  { quote: "Compound interest is the most powerful force in the universe.", author: "Attributed to Albert Einstein" },
  { quote: "Do not work for money; make your money work for you.", author: "Robert Kiyosaki" },
  { quote: "Frugality is the daughter of prudence and the sister of temperance.", author: "Unknown" },
  { quote: "The key to wealth is compound consistency.", author: "Unknown" },
  { quote: "Wealth is a tool of freedom, not display.", author: "Unknown" },
  { quote: "Keep your habits positive, because your habits become your values.", author: "Mahatma Gandhi" },
  { quote: "Small acts of discipline build a lifetime of success.", author: "Unknown" },
  { quote: "The intelligent investor looks for value, not hype.", author: "Benjamin Graham" },
  { quote: "Never buy things you do not need with money you do not have.", author: "Unknown" },
  { quote: "Consistency beats talent when talent fails to be consistent.", author: "Unknown" },
  { quote: "An emergency fund is the best insurance policy.", author: "Dave Ramsey" },
  { quote: "Discipline is the differentiator.", author: "Unknown" },
  { quote: "If you do not plan, you plan to fail.", author: "Benjamin Franklin" },
  { quote: "Frugality is simple: get maximum value for every dollar.", author: "Unknown" },
  { quote: "The rich invest in time. The poor invest in money.", author: "Warren Buffett" },
  { quote: "Live like no one else now so that you can live like no one else later.", author: "Dave Ramsey" },
  { quote: "Invest in what you understand. Avoid what you don't.", author: "Peter Lynch" },
  { quote: "Wealth is the shield of the wise.", author: "Unknown" },
  { quote: "Discipline is doing what needs to be done even if you don't want to.", author: "Unknown" },
  { quote: "Long-term compounding is magic. Do not interrupt it needlessly.", author: "Charlie Munger" },
  { quote: "A penny saved is a shield against bad times.", author: "Unknown" },
  { quote: "Consistency leads to mastery.", author: "Unknown" },
  { quote: "Spend on assets that pay you. Spend less on liabilities that cost you.", author: "Unknown" },
  { quote: "The secret to financial success is living below your income.", author: "Unknown" },
  { quote: "Your habits determine your future net worth.", author: "James Clear" },
  { quote: "Frugal living is creative living.", author: "Unknown" },
  { quote: "Discipline is the bedrock of character.", author: "Unknown" },
  { quote: "Wealth is option value. Keep your options open.", author: "Naval Ravikant" },
  { quote: "Buy assets. Avoid debts. Build freedom.", author: "Unknown" },
  { quote: "Patience pays. Impatience costs.", author: "Unknown" },
  { quote: "The key to productivity is focusing on the essential.", author: "Greg McKeown" },
  { quote: "Consistency of effort is what leads to accomplishment.", author: "Unknown" },
  { quote: "Control your costs before they control you.", author: "Unknown" },
  { quote: "Financial peace of mind is not having a lot of stuff. It's having no debt.", author: "Dave Ramsey" },
  { quote: "Self-discipline is the master key to riches.", author: "Napoleon Hill" },
  { quote: "Invest in assets. Liabilities will come later.", author: "Unknown" },
  { quote: "The price of discipline is always less than the pain of regret.", author: "Nido Qubein" },
  { quote: "Wealth is built in silence. Enjoy the peace.", author: "Unknown" },
  { quote: "Frugality is not about spending less; it is about spending intentionally.", author: "Unknown" },
  { quote: "Consistency is what makes average effort great.", author: "Unknown" },
  { quote: "Never buy a thing because it is cheap; buy it because it is useful.", author: "Unknown" },
  { quote: "Compound habits yield compound wealth.", author: "James Clear" },
  { quote: "The best investment is in your own mind.", author: "Benjamin Franklin" },
  { quote: "Discipline is the core of freedom.", author: "Unknown" },
  { quote: "Wealth is the buffer against life's uncertainties.", author: "Unknown" },
  { quote: "Patience in savings is power in spending.", author: "Unknown" },
  { quote: "The stock market is a device for compounding capital.", author: "Unknown" },
  { quote: "Live simply so that others may simply live.", author: "Elizabeth Ann Seton" },
  { quote: "Consistency of purpose is the key to achievement.", author: "Unknown" },
  { quote: "Discipline beats motivation every day.", author: "Unknown" },
  { quote: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
  { quote: "Financial intelligence is the ability to generate cash flow.", author: "Robert Kiyosaki" },
  { quote: "A budget is the ultimate tool of control.", author: "Unknown" },
  { quote: "Wealth is the result of saving and investing over time.", author: "Unknown" },
  { quote: "Consistency builds confidence and competence.", author: "Unknown" },
  { quote: "Frugality is the foundation of generosity.", author: "Unknown" },
  { quote: "Invest in businesses that a fool could run, because one day a fool will.", author: "Warren Buffett" },
  { quote: "Discipline is the compass of the soul.", author: "Unknown" },
  { quote: "Long term thinking is a superpower.", author: "Unknown" },
  { quote: "Compound interest is the ladder of financial growth.", author: "Unknown" },
  { quote: "The secret to productivity is delegation and focus.", author: "Peter Drucker" },
  { quote: "Consistency turns actions into habits.", author: "Unknown" },
  { quote: "Save money today. It will save you tomorrow.", author: "Unknown" },
  { quote: "Frugality is elegance in spending.", author: "Unknown" },
  { quote: "Wealth is built by compounding assets, not salary.", author: "Naval Ravikant" },
  { quote: "Discipline is the root of freedom.", author: "Jocko Willink" },
  { quote: "Take care of the margins, and the core will take care of itself.", author: "Unknown" },
  { quote: "Consistency is the mother of mastery.", author: "Robin Sharma" },
  { quote: "Spend on what is essential; save on what is extra.", author: "Unknown" },
  { quote: "Long term compounding is built on patience.", author: "Unknown" },
  { quote: "Your mind is your greatest asset. Educate it.", author: "Robert Kiyosaki" },
  { quote: "Discipline is the engine of progress.", author: "Unknown" },
  { quote: "Wealth is not about having a full garage; it is about having a free mind.", author: "Unknown" },
  { quote: "Frugality is the key to financial safety.", author: "Unknown" },
  { quote: "Consistency beats intensity.", author: "Unknown" },
  { quote: "Save first, spend second.", author: "Unknown" },
  { quote: "A wise investor ignores the crowds.", author: "Jack Bogle" },
  { quote: "Discipline is the pathway to success.", author: "Unknown" },
  { quote: "Wealth is quiet security.", author: "Unknown" },
  { quote: "Live below your means. Compound the rest.", author: "Unknown" },
  { quote: "Consistency is the bridge to mastery.", author: "Unknown" },
  { quote: "Do not borrow to buy assets that depreciate.", author: "Dave Ramsey" },
  { quote: "Patience leads to wisdom.", author: "Unknown" },
  { quote: "Frugality is a sign of financial maturity.", author: "Unknown" },
  { quote: "Discipline is the master of fate.", author: "Unknown" },
  { quote: "Wealth is options. Save to expand them.", author: "Unknown" },
  { quote: "Consistency of discipline builds mountains of wealth.", author: "Unknown" }
];
